# Generated by Django 5.2.1 on 2025-05-18 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0002_alter_projectmember_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolepermission',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='role',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='role',
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
