# Generated by Django 5.2.1 on 2025-05-19 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_tenant_options'),
        ('projects', '0004_activitylog_project_comment_project_sprint_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labels', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='label',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label', to='accounts.tenant'),
        ),
    ]
