# Generated by Django 5.2.1 on 2025-05-19 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_tenant_options'),
        ('projects', '0005_label_project_alter_label_tenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='metadata',
            new_name='changed_fields',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='target_repr',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='target_type',
            field=models.CharField(default='Task', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='projects.comment'),
        ),
    ]
