# Generated by Django 5.2.1 on 2025-05-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tenant', 'verbose_name_plural': 'Tenants'},
        ),
    ]
